from Main_code.Menu import main
import pygame 
import os

# This file is for the user to execute !!!!!!!!!!!!!
screen_width = 900
screen_height = 620
screen = pygame.display.set_mode((screen_width, screen_height))
pygame.display.set_caption("Introduction Ultimaze")
gameIcon = pygame.image.load(os.path.join("Images", "logo_ultimaze.jpg"))
pygame.display.set_icon(gameIcon)
# Colors

black = (0, 0, 0)
white = (255, 255, 255)

#Image
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_22.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_21.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_20.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_19.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_18.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_17.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_16.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_15.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_14.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_13.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_12.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_11.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_10.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_9.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_8.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_7.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_6.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_5.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_4.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_3.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_2.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro_1.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(100)
menu_image = pygame.image.load(os.path.join("Images", "Game_intro.png"))
screen.blit(menu_image,(0,0))
pygame.display.update()
pygame.time.wait(300)


main()